### ISSUE TITLE
[research] http description language

### ISSUE THREAD

**Issue by dignifiedquire** [ipfs/http-api-spec#6]
These three are the main ones coming up 
- http://raml.org/
- https://apiblueprint.org/ and https://apiary.io/ https://github.com/apiaryio/mson
- http://swagger.io/
### Comparisons
- Relatively new (beginning of this year) HN thread: https://news.ycombinator.com/item?id=8912897
- https://lonelyplanet.atlassian.net/wiki/display/PUB/API+Specification%2C+Automated+Testing%2C+and+Documentation+Generation+Discussion

---

My current feeling from reading all of this is that API Blueprint in combination with apiary seems to be the best solution.

**Comment by RichardLitt** [comment]
My current feeling is that Swagger is confusing and hard to validate easily. You seem to have gotten apiary up easily, so maybe that is better.

**Comment by dignifiedquire** [comment]
After some discussion with @RichardLitt we will use api blueprint in combination with apiary.io for now

**Comment by RichardLitt** [comment]
:palm_tree:

**Comment by RichardLitt** [comment]
For archival purposes:

10:55 AM <dignifiedquire> richardlitt: did you have a chance to look at apiary in more detail? I think I will just start documenting the current http api in there for now and try to run some tests with it against js-ipfs-api and go-ipfs
10:56 AM <dignifiedquire> otherwise I’m afraid to be writing abstract specs that are of little use to the current efforts in that space
10:58 AM → cryptotec joined  ⇐ warner quit  
10:59 AM <richardlitt> dignifiedquire: I didn't, but that sounds like the right move for me.
11:00 AM <richardlitt> dignifiedquire: your example of add on there looked loads better than my faulty swagger implementation, which could then hypothetically be routed into the pretty three-column thing we were looking at (forget the name right now, but it's one of the reasons we were going with Swagger at all)
11:01 AM ⇐ cryptotec quit (~cryptotec@178.197.235.245) Read error: Connection reset by peer
11:01 AM <richardlitt> dignifiedquire: ah, it was readme.io
11:02 AM <dignifiedquire> right, but with apiary we actually don’t need that right?
11:02 AM <richardlitt> exactly
11:02 AM ⇐ s_kunk quit (~s_kunk@unaffiliated/s-kunk/x-5139101) Ping timeout: 250 seconds
11:02 AM <richardlitt> I think readme.io is a product we were using because a) other companies use it b) it looks pretty. The issue is that it all has to be done manually, or imported using swagger
11:02 AM <dignifiedquire> yeah had the exact same feeling when I was looking at swagger, just was like turning head here and there and not being able to orient my sefl
11:03 AM <richardlitt> I continually had issues understanding the swagger docs (Likely not their fault, much more likely my issues separating out level 1 and level 2 specs, as well as CLI vs HTTP stuff, and my own confusion about end point in general)
11:03 AM <richardlitt> I don't think swagger will work for our level of abstraction, given how hard it was for me to grok that, and how poor their validation tools are
11:04 AM <dignifiedquire> also writing the specs in markdown is really nice: https://github.com/Dignifiedquire/ipfs-http-api/blob/master/apiary.apib
11:04 AM <richardlitt> That was the apiary markdown format?
11:04 AM → reit joined (~reit@unaffiliated/reit)
11:04 AM <dignifiedquire> yes
11:04 AM <dignifiedquire> that’s the source of my add example
11:05 AM <richardlitt> Well, it looks pretty clean to me
11:05 AM <dignifiedquire> for lvl2-cli and lvl1 we will have to resort to other methods, that’s why I also think to start with http is better as there is already a lot of tooling that we can use to kickstart our efforts, rather than having to write all of it ourselves
11:05 AM <richardlitt> aye
11:06 AM <dignifiedquire> that’s the format: https://apiblueprint.org/
11:06 AM <richardlitt> Well, I think starting with something cleaner than swagger yaml or JSON is probably smart
11:06 AM <dignifiedquire> yep
11:06 AM <richardlitt> So... go ahead with apiary
11:06 AM <dignifiedquire> okay will do
